# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: firsttracks

service: itinerary-watch

provider:
  name: aws
  region: us-east-2
  runtime: python3.14
  architecture: arm64
  logRetentionInDays: 30
  httpApi:
    cors:
      allowedOrigins:
        - https://www.itinerarywatch.com
      allowedMethods:
        - POST
        - GET
        - OPTIONS     # Needed for CORS preflight to pass
      allowedHeaders:
        - Content-Type
        - Accept
        - Accepts
      exposedHeaders:
        - WWW-Authenticate
      allowCredentials: true    # signals to frontend it's okay (necessary, even) to attach cookies to this call
    disableDefaultEndpoint: true

package:
  individually: true              # Packages all functions into their own independent ZIP file
  patterns:
    - '!**'                       # Default is ignore everything

functions:

  db_maintenance:
    events:
      - schedule: cron(1 0 * * ? *)   # EventBridge scheduled event at 00:01 UTC every day
    role: arn:aws:iam::293119271420:role/ItineraryWatch_Lambda
    handler: src/db_maintenance.lambda_entry_point_event_bridge
    memorySize: 256
    timeout: 20 # 20 second runtime to be safe
    package:
      patterns:
        - 'src/db_maintenance.py'
        - 'src/aws-rds-global-bundle.pem'

  scraper_launcher:
    events:
      - schedule: cron(0 * * * ? *)   # EventBridge scheduled event on the hour, every hour
    role: arn:aws:iam::293119271420:role/ItineraryWatch_Lambda
    handler: src/scraper_launcher.lambda_entry_point_event_bridge
    memorySize: 256
    timeout: 20 # 20 second runtime to be safe
    package:
      patterns:
        - 'src/scraper_launcher.py'
        - 'src/aws-rds-global-bundle.pem'

  itinerary_watch_scraper:
    events:
      - sns: arn:aws:sns:us-east-2:293119271420:itinerary_watch_scraper_trigger
    role: arn:aws:iam::293119271420:role/ItineraryWatch_Lambda
    handler: src/itinerary_watch_scraper.lambda_entry_point_sns
    memorySize: 512
    timeout: 60
    package:
      patterns:
        - 'src/itinerary_watch_scraper.py'
        - 'src/cruise_day_detail.py'
        - 'src/cruise_sailing.py'
        - 'src/cruise_lines/*.py'
        - 'src/aws-rds-global-bundle.pem'

  itinerary_change_detection:
    events:
      - schedule: cron(0 * * * ? *)   # EventBridge scheduled event on the hour, every hour
    role: arn:aws:iam::293119271420:role/ItineraryWatch_Lambda
    handler: src/itinerary_change_detection.lambda_entry_point_event_bridge
    memorySize: 256
    timeout: 20 # 20 second runtime to be safe
    package:
      patterns:
        - 'src/itinerary_change_detection.py'
        - 'src/aws-rds-global-bundle.pem'

  customer_notifier:
    events:
      - sns: arn:aws:sns:us-east-2:293119271420:itinerary_watch_user_notifier
    role: arn:aws:iam::293119271420:role/ItineraryWatch_Lambda
    handler: src/customer_notifier.lambda_entry_point_sns
    memorySize: 512
    timeout: 60
    package:
      patterns:
        - 'src/customer_notifier.py'
        - 'src/aws-rds-global-bundle.pem'

  oauth_callback_google:
    role: arn:aws:iam::293119271420:role/ItineraryWatch_Lambda
    handler: src/web_api/oauth_callback_google.lambda_handler_apigw
    memorySize: 1769
    events:
      - httpApi:
          method: POST
          path: /oauth/callback/google
    warmup:
      default:
        enabled: true   # Avoid cold start as it's user facing' ping every five mins to keep resident
    package:
      patterns:
        - 'src/web_api/oauth_callback_google.py'
        - 'src/aws-rds-global-bundle.pem'

  api_user:
    role: arn:aws:iam::293119271420:role/ItineraryWatch_Lambda
    handler: src/web_api/api_user.lambda_handler_apigw
    memorySize: 1769
    events:
      - httpApi:
          method: GET
          path: /api/v001/user
    warmup:
      default:
        enabled: true   # Avoid cold start as it's user facing' ping every five mins to keep resident
    package:
      patterns:
        - 'src/web_api/api_user.py'
        - 'src/aws-rds-global-bundle.pem'


plugins:
  - serverless-domain-manager
  - serverless-plugin-warmup

custom:
  pythonRequirements:
    useUv: true                   # Automatically processes your uv.lock
    installer: uv                 # Fast dependency resolution using uv binary

    # Don't package python deps that are already in lambda environment or are for types only
    noDeploy:
      - boto3
      - botocore
      - jmespath
      - s3transfer
      - boto3-stubs
      - botocore-stubs
      - types-awscrt
      - types-s3transfer
  customDomain:
    domainName: api.itinerarywatch.com
    stage: ${sls:stage}
    basePath: ''                # Serves your API from the root path (/)
    certificateName: 'api.itinerarywatch.com' # The plugin will request/look up this cert name
    createRoute53Record: true   # Automatically adds A/AAAA records to Route 53
    endpointType: REGIONAL      # MUST be REGIONAL for API Gateway v2 (HTTP APIs)
    securityPolicy: tls_1_2     # Required protocol security standard
    apiType: http               # MUST be 'http' to target API Gateway v2
    autoDomain: true            # Automates domain creation on 'sls deploy'
  warmup:
    default:
      enabled: false    # warmup (ping every five mins) is optional, not enabled for ALL functions
      prewarm: true     # Any functions that enable this warmer get loaded immediateluy on deploy, no five min cold window
