# serverless.yml
service: itinerary-watch

provider:
  name: aws
  runtime: python3.14
  architecture: arm64

package:
  individually: true              # Packages all functions into their own independent ZIP file
  patterns:
    - '!**'                       # Default is ignore everything

functions:
  db_maintenance:
    role: arn:aws:iam::293119271420:role/ItineraryWatch_Lambda
    handler: src/db_maintenance.lambda_entry_point_event_bridge
    memorySize: 256
    timeout: 20 # 20 second runtime in case
    package:
      patterns:
        - 'src/db_maintenance.py'
        - 'src/aws-rds-global-bundle.pem'

custom:
  pythonRequirements:
    useUv: true                   # Automatically processes your uv.lock
    installer: uv                 # Fast dependency resolution using uv binary