# serverless.yml
service: itinerary-watch

provider:
  name: aws
  runtime: python3.14             # Supports the latest managed python standard
  architecture: arm64

package:
  individually: true             # 1. Packages this function into its own independent ZIP file
  patterns:
    - '!**'                   # Default is ignore everything

functions:
  db_maintenance:
    role: arn:aws:iam::293119271420:role/ItineraryWatch_Lambda
    handler: src/db_maintenance.lambda_entry_point_event_bridge
    memorySize: 256
    timeout: 20 # 20 second runtime in case
    package:
      # 2. Assign the patterns directly to the function to isolate the execution scope
      patterns:
        - 'src/db_maintenance.py' # 3. Explicitly bundle the target module file
        - 'src/aws-rds-global-bundle.pem'

custom:
  pythonRequirements:
    useUv: true                   # Automatically processes your uv.lock
    installer: uv                 # Fast dependency resolution using uv binary
